services:
  backend:
    build:
      context: ./backend/Board
      dockerfile: Dockerfile
    container_name: kanban-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_H2_CONSOLE_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kanban-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/kanban-board-client-app
      dockerfile: Dockerfile
    container_name: kanban-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - kanban-network
    restart: unless-stopped

networks:
  kanban-network:
    driver: bridge

volumes:
  kanban-data: 