/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDTO } from './userDTO';


export interface AttachmentDTO { 
    id?: number;
    filename: string;
    originalFilename: string;
    fileUrl: string;
    contentType: string;
    fileSize: number;
    taskId?: number;
    uploadedBy?: UserDTO;
    createdAt?: Date;
    updatedAt?: Date;
}

