/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDTO } from './userDTO';
import { LabelDTO } from './labelDTO';
import { ColumnDTO } from './columnDTO';


export interface BoardDTO { 
    id?: number;
    name: string;
    description?: string;
    settings?: string;
    invitationCode?: string;
    archived?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
    createdBy?: UserDTO;
    columns?: Array<ColumnDTO>;
    labels?: Array<LabelDTO>;
}

