/**
 * Kanban API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnDTO } from './columnDTO';


export interface BoardDTO { 
    id?: number;
    name?: string;
    columns?: Array<ColumnDTO>;
}

