/**
 * Kanban API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskPreviewDTO } from './taskPreviewDTO';


export interface ColumnDTO { 
    id?: number;
    name: string;
    tasks?: Array<TaskPreviewDTO>;
}

