/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskDTO } from './taskDTO';

export interface ColumnDTO {
  id?: number;
  name: string;
  orderIndex?: number;
  color?: string;
  taskLimit?: number;
  createdAt?: Date;
  updatedAt?: Date;
  tasks?: Array<TaskDTO>;
}
