/**
 * Kanban API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Task } from './task';


export interface Comment { 
    id?: number;
    content?: string;
    task?: Task;
}

