/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LabelDTO { 
    id?: number;
    name: string;
    color: string;
    description?: string;
    boardId?: number;
    createdAt?: Date;
    updatedAt?: Date;
}

