/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDTO } from './userDTO';

export interface NotificationDTO {
  id?: number;
  title: string;
  message: string;
  type: string;
  read?: boolean;
  data?: string;
  recipientId?: number;
  senderId?: number;
  taskId?: number;
  boardId?: number;
  recipient?: UserDTO;
  sender?: UserDTO;
  createdAt?: Date;
  readAt?: Date;
}
