/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PerformanceMetrics {
  totalBoards?: number;
  totalTasks?: number;
  totalUsers?: number;
  activeBoards?: number;
  recentTasks?: number;
  lastOptimization?: Date;
}
