/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductivityMetrics { 
    boardId?: number;
    fromDate?: Date;
    toDate?: Date;
    tasksCreated?: number;
    tasksCompleted?: number;
    completionRate?: number;
    averageTaskDuration?: number;
}

