/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Role data transfer object for API communication
 */
export interface RoleDTO { 
    /**
     * Unique identifier for the role
     */
    id?: number;
    /**
     * Name of the role
     */
    name: string;
}

