/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SystemAnalytics {
  totalUsers?: number;
  activeUsers?: number;
  totalBoards?: number;
  totalTasks?: number;
  completedTasks?: number;
  overdueTasks?: number;
  totalComments?: number;
  averageCompletionTime?: number;
  statusDistribution?: { [key: string]: number };
  priorityDistribution?: { [key: string]: number };
}
