/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentDTO } from './attachmentDTO';
import { UserDTO } from './userDTO';
import { CommentDTO } from './commentDTO';
import { LabelDTO } from './labelDTO';


export interface TaskDTO { 
    id?: number;
    title: string;
    description?: string;
    priority?: string;
    status?: string;
    dueDate?: Date;
    createdAt?: Date;
    updatedAt?: Date;
    comments?: Array<CommentDTO>;
    attachments?: Array<AttachmentDTO>;
    labels?: Array<LabelDTO>;
    createdBy?: UserDTO;
    assignee?: UserDTO;
}

