/**
 * Kanban API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentDTO } from './commentDTO';


export interface TaskDTO { 
    id?: number;
    title?: string;
    description?: string;
    comments?: Array<CommentDTO>;
}

