/**
 * Kanban API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDTO {
    id?: number;
    username?: string;
    name?: string; // Legacy field for backward compatibility
    displayName?: string; // New field for display purposes
    roles?: string[];
}

