/**
 * Kanban Board API
 *
 * Contact: support@kanbanboard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserAnalytics { 
    userId?: number;
    username?: string;
    displayName?: string;
    assignedTasks?: number;
    createdTasks?: number;
    completedTasks?: number;
    overdueTasks?: number;
    completionRate?: number;
    statusDistribution?: { [key: string]: number; };
    priorityDistribution?: { [key: string]: number; };
}

